alphabet = [
    {"letter": "A", "name": "ACE", "value": 6, "pronunciation": "AH", "meaning": "Forçar\nCriar uma ponte\nCriar"},
    {"letter": "B", "name": "BA", "value": 4, "pronunciation": "BAH", "meaning": "Segurar\nConter\nRedesenhar\nLevar Tempo\nDemorar\nCorrigir e aperfeiçoar"},
    {"letter": "C", "name": "CESE", "value": 6, "pronunciation": "CUH", "meaning": "Lutar\nOuvir"},
    {"letter": "D", "name": "DE (DEE)", "value": 7, "pronunciation": "DAH", "meaning": "Deixar como está\bMostrar apoio"},
    {"letter": "E", "name": "DEF", "value": 8, "pronunciation": "EH", "meaning": "Ter os desejos realizados\nVer o que deseja e conseguir\nTransformar os desejos em realidade"},
    {"letter": "F1", "name": "HE", "value": 9, "pronunciation": "FUH", "meaning": "Manter coisas em segredo\nTemer"},
    {"letter": "F2", "name": "SED (SEED)", "value": 10, "pronunciation": "FIE", "meaning": "Escapar\nAproveitar\nTemer"},
    {"letter": "F", "name": "AEB", "value": 11, "pronunciation": "FAY", "meaning": "Acertar em cheio\nSe redimir\nReceber dinheiro"},
    {"letter": "G", "name": "DEIF (DEEEF)", "value": 12, "pronunciation": "GAHEE", "meaning": "Espalhar\nEsticar"},
    {"letter": "H", "name": "HAS (HAHS)", "value": 13, "pronunciation": "HAH", "meaning": "Abrir as asas\bMelhorar"},
    {"letter": "I", "name": "EE", "value": 14, "pronunciation": "EE", "meaning": "Falar\bEscrever\bPrometer"},
    {"letter": "J", "name": "HEB (HEEB)", "value": 15, "pronunciation": "JAY", "meaning": "Resistir à mudança\bResistir\bManter a honra\bTer boa sorte\bEsperar mudanças"},
    {"letter": "K", "name": "KEY (KEE)", "value": 16, "pronunciation": "KAH", "meaning": "Correr\bColocar pressão\bEnfatizar"},
    {"letter": "L", "name": "LED", "value": 17, "pronunciation": "LUH", "meaning": "Reformular\bSe apaixonar\bRedesenhar"},
    {"letter": "M", "name": "CHIF", "value": 18, "pronunciation": "MEH", "meaning": "Estar reflexivo\nEscutar\nEstar certo, ter certeza"},
    {"letter": "N", "name": "ADE", "value": 19, "pronunciation": "ENN", "meaning": "Pensar em silêncio\nPrecisar"},
    {"letter": "O", "name": "TEUPE (TEE-UP-EE)", "value": 5, "pronunciation": "OH-AY", "meaning": "Transgredi\nGanhar"},
    {"letter": "P", "name": "AED", "value": 6, "pronunciation": "PAH", "meaning": "Preparar a Vontade\nDobrar\ncurvar"},
    {"letter": "Q", "name": "EDES (EE-DEES)", "value": 7, "pronunciation": "KWA", "meaning": "Deixar algo ir\nNão ter esperança\nEstar pronto"},
    {"letter": "R1", "name": "DEIF (DAY-IF)", "value": 7, "pronunciation": "RRR", "meaning": "Soltar o ódio\nAjustar"},
    {"letter": "R2", "name": "DADA (DAY-DA)", "value": 8, "pronunciation": "RAY", "meaning": "Soltar fardos\nAumentar vibração"},
    {"letter": "S", "name": "HID", "value": 3, "pronunciation": "SAH", "meaning": "Desejar (luxúria)\nUnir desejos\nJuntar, descansar"},
    {"letter": "T", "name": "ADEF", "value": 1, "pronunciation": "TEE", "meaning": "Fazer uma jornada, Sentir o crescimento\nSe sentir culpado sobre algo"},
    {"letter": "U", "name": "DAEF (DAY-EF)", "value": 5, "pronunciation": "OO-AY", "meaning": "Aumentar\nSer confiável\nConsertar erros\nFazer um trabalho detalhado"},
    {"letter": "V1", "name": "GES (JES)", "value": 11, "pronunciation": "VEE", "meaning": "Preparar\nTrazer à existência algo, Confundir"},
    {"letter": "V2", "name": "DAEF (DAY-EF)", "value": 12, "pronunciation": "VAY", "meaning": "Reestruturar a realidade"},
    {"letter": "W", "name": "ASDE (ASDEE)", "value": 3, "pronunciation": "WAY", "meaning": "Mudar a cabeça\nEstar feliz com um resultado"},
    {"letter": "X", "name": "DEM", "value": 1, "pronunciation": "KEY", "meaning": "Merecer\nSer respeitado\nSer honesto"},
    {"letter": "Y", "name": "EB", "value": 2, "pronunciation": "YEE", "meaning": "Ver mudança nos outros\nOlhar de perto\nMudar uma atitude ou perspectiva"},
    {"letter": "Z", "name": "EDE (EEDAY)", "value": 91, "pronunciation": "ZIE", "meaning": "Ser sutil\nVer a sua habilidade\nFazer uma jornada"},
]