alphabet = [
    {"letter": "A", "name": "ACE", "value": 6, "pronunciation": "AH", "meaning": "Forçar, Criar um ponte, Criar"},
    {"letter": "B", "name": "BA", "value": 4, "pronunciation": "BAH", "meaning": "Segurar, Conter, Redesenhar, Levar Tempo, Demorar, Corrigir e aperfeiçoar"},
    {"letter": "C", "name": "CESE", "value": 6, "pronunciation": "CUH", "meaning": "Lutar, Ouvir"},
    {"letter": "D", "name": "DE (DEE)", "value": 7, "pronunciation": "DAH", "meaning": "Deixar como está, Mostrar apoio"},
    {"letter": "E", "name": "DEF", "value": 8, "pronunciation": "EH", "meaning": "Ter os desejos realizados, Ver o que deseja e conseguir, Transformar os desejos em realidade"},
    {"letter": "F1", "name": "HE", "value": 9, "pronunciation": "FUH", "meaning": "Manter coisas em segredo, Temer"},
    {"letter": "F2", "name": "SED (SEED)", "value": 10, "pronunciation": "FIE", "meaning": "Escapar, Aproveitar, Temer"},
    {"letter": "F", "name": "AEB", "value": 11, "pronunciation": "FAY", "meaning": "Acertar em cheio, Se redimir, Receber dinheiro"},
    {"letter": "G", "name": "DEIF (DEEEF)", "value": 12, "pronunciation": "GAHEE", "meaning": "Espalhar, Esticar"},
    {"letter": "H", "name": "HAS (HAHS)", "value": 13, "pronunciation": "HAH", "meaning": "Abrir as asas, Melhorar"},
    {"letter": "I", "name": "EE", "value": 14, "pronunciation": "EE", "meaning": "Falar, Escrever, Prometer"},
    {"letter": "J", "name": "HEB (HEEB)", "value": 15, "pronunciation": "JAY", "meaning": "Resistir à mudança, Resistir, Manter a honra, Ter boa sorte, Esperar mudanças"},
    {"letter": "K", "name": "KEY (KEE)", "value": 16, "pronunciation": "KAH", "meaning": "Correr, Colocar pressão, Enfatizar"},
    {"letter": "L", "name": "LED", "value": 17, "pronunciation": "LUH", "meaning": "Reformular, Se apaixonar, Redesenhar"},
    {"letter": "M", "name": "CHIF", "value": 18, "pronunciation": "MEH", "meaning": "Estar reflexivo, Escutar, Estar certo, ter certeza"},
    {"letter": "N", "name": "ADE", "value": 19, "pronunciation": "ENN", "meaning": "Pensar em silêncio, Precisar"},
    {"letter": "O", "name": "TEUPE (TEE-UP-EE)", "value": 5, "pronunciation": "OH-AY", "meaning": "Transgredir, Ganhar"},
    {"letter": "P", "name": "AED", "value": 6, "pronunciation": "PAH", "meaning": "Preparar a Vontade, Dobrar, curvar"},
    {"letter": "Q", "name": "EDES (EE-DEES)", "value": 7, "pronunciation": "KWA", "meaning": "Deixar algo ir, Não ter esperança, Estar pronto"},
    {"letter": "R1", "name": "DEIF (DAY-IF)", "value": 7, "pronunciation": "RRR", "meaning": "Soltar o ódio, Ajustar"},
    {"letter": "R2", "name": "DADA (DAY-DA)", "value": 8, "pronunciation": "RAY", "meaning": "Soltar fardos, Aumentar vibração"},
    {"letter": "S", "name": "HID", "value": 3, "pronunciation": "SAH", "meaning": "Desejar (luxúria), Unir desejos, Juntar, descansar"},
    {"letter": "T", "name": "ADEF", "value": 1, "pronunciation": "TEE", "meaning": "Fazer uma jornada, Sentir o crescimento, Se sentir culpado sobre algo"},
    {"letter": "U", "name": "DAEF (DAY-EF)", "value": 5, "pronunciation": "OO-AY", "meaning": "Aumentar, Ser confiável, Consertar erros, Fazer um trabalho detalhado"},
    {"letter": "V1", "name": "GES (JES)", "value": 11, "pronunciation": "VEE", "meaning": "Preparar, Trazer à existência algo, Confundir"},
    {"letter": "V2", "name": "DAEF (DAY-EF)", "value": 12, "pronunciation": "VAY", "meaning": "Reestruturar a realidade"},
    {"letter": "W", "name": "ASDE (ASDEE)", "value": 3, "pronunciation": "WAY", "meaning": "Mudar a cabeça, Estar feliz com um resultado"},
    {"letter": "X", "name": "DEM", "value": 1, "pronunciation": "KEY", "meaning": "Merecer, Ser respeitado, Ser honesto"},
    {"letter": "Y", "name": "EB", "value": 2, "pronunciation": "YEE", "meaning": "Ver mudança nos outros, Olhar de perto, Mudar uma atitude ou perspectiva"},
    {"letter": "Z", "name": "EDE (EEDAY)", "value": 91, "pronunciation": "ZIE", "meaning": "Ser sutil, Ver a sua habilidade, Fazer uma jornada"},
]