astrology = {
    "sun_signs": {
        "aries": "Energia, ação e iniciativa. Personalidade impulsiva, corajosa e independente.",
        "taurus": "Estabilidade, paciência e praticidade. Valorização do conforto e segurança.",
        "gemini": "Comunicação, curiosidade e adaptabilidade. Personalidade versátil e mentalmente ágil.",
        "cancer": "Emoção, cuidado e proteção. Personalidade sensível e apegada ao lar e à família.",
        "leo": "Autoconfiança, criatividade e liderança. Gosto por ser o centro das atenções e brilhar.",
        "virgo": "Organização, análise e eficiência. Foco em detalhes e busca por aperfeiçoamento.",
        "libra": "Harmonia, justiça e colaboração. Personalidade sociável, buscando equilíbrio nos relacionamentos.",
        "scorpio": "Intensidade, transformação e mistério. Personalidade profunda e emocionalmente intensa.",
        "sagittarius": "Otimismo, liberdade e busca por conhecimento. Aprecia aventura e expansão de horizontes.",
        "capricorn": "Ambição, disciplina e responsabilidade. Foco em realizações concretas e no sucesso a longo prazo.",
        "aquarius": "Originalidade, inovação e independência. Gosta de ideias progressistas e de seguir seu próprio caminho.",
        "pisces": "Sensibilidade, imaginação e compaixão. Personalidade intuitiva e sonhadora, com forte conexão espiritual."
    },
    "moon_signs": {
        "aries": "Emoções impulsivas, diretas e intensas. Reage de forma imediata e pode ser impaciente.",
        "taurus": "Emoções estáveis e profundas. Busca segurança emocional e conforto nos relacionamentos.",
        "gemini": "Emoções leves e variáveis. Necessidade de comunicação e estimulação mental para se sentir bem.",
        "cancer": "Emoções profundas e sensíveis. Forte ligação com o lar, a família e a segurança emocional.",
        "leo": "Emoções dramáticas e intensas. Gosta de ser reconhecida e valorizada nos relacionamentos.",
        "virgo": "Emoções práticas e contidas. Analisa suas emoções e pode buscar servir aos outros para se sentir útil.",
        "libra": "Emoções equilibradas e sociáveis. Busca harmonia nos relacionamentos e evita conflitos.",
        "scorpio": "Emoções intensas, profundas e transformadoras. Reage de forma poderosa e pode ser desconfiada.",
        "sagittarius": "Emoções otimistas e expansivas. Precisa de liberdade e aventura para se sentir emocionalmente bem.",
        "capricorn": "Emoções controladas e reservadas. Busca segurança e estabilidade emocional, com foco em objetivos a longo prazo.",
        "aquarius": "Emoções desapegadas e inovadoras. Precisa de independência emocional e relações baseadas na amizade.",
        "pisces": "Emoções sensíveis, compassivas e imaginativas. Reage de forma intuitiva e busca conexão emocional profunda."
    },
    "mercury_signs": {
        "aries": "Pensamento rápido e direto. Comunicação assertiva, com tendência à impaciência.",
        "taurus": "Pensamento lento e prático. Comunicação clara, focada no que é concreto e útil.",
        "gemini": "Pensamento ágil e curioso. Comunicação versátil, com interesse em aprender e compartilhar ideias.",
        "cancer": "Pensamento emocional e protetor. Comunicação intuitiva, com foco em sentimentos e segurança.",
        "leo": "Pensamento criativo e confiante. Comunicação dramática, com desejo de ser ouvido e admirado.",
        "virgo": "Pensamento analítico e detalhado. Comunicação prática e eficiente, com foco na precisão.",
        "libra": "Pensamento equilibrado e diplomático. Comunicação harmônica, com foco em justiça e parcerias.",
        "scorpio": "Pensamento profundo e investigativo. Comunicação intensa, focada em descobrir verdades ocultas.",
        "sagittarius": "Pensamento filosófico e expansivo. Comunicação aberta, com interesse em explorar novas ideias e culturas.",
        "capricorn": "Pensamento estruturado e prático. Comunicação séria e focada em objetivos a longo prazo.",
        "aquarius": "Pensamento inovador e excêntrico. Comunicação original, com foco em ideias progressistas e sociais.",
        "pisces": "Pensamento imaginativo e intuitivo. Comunicação sensível, com foco em ideias abstratas e emocionais."
    },
    "venus_signs": {
        "aries": "Valoriza a independência e a emoção nos relacionamentos. Gosta de conexões rápidas e intensas.",
        "taurus": "Valoriza o conforto, a estabilidade e os prazeres sensoriais. Busca relacionamentos duradouros e tranquilos.",
        "gemini": "Valoriza a inteligência e a comunicação nos relacionamentos. Gosta de variedade e troca de ideias.",
        "cancer": "Valoriza a segurança emocional e o carinho. Procura relacionamentos sensíveis e protetores.",
        "leo": "Valoriza a diversão e a admiração nos relacionamentos. Gosta de ser o centro das atenções e de demonstrações públicas de afeto.",
        "virgo": "Valoriza a praticidade e a eficiência nos relacionamentos. Mostra o amor por meio de gestos de cuidado e apoio.",
        "libra": "Valoriza a harmonia, a beleza e o equilíbrio nos relacionamentos. Busca parcerias justas e agradáveis.",
        "scorpio": "Valoriza a intensidade e a profundidade emocional. Gosta de relacionamentos apaixonados e transformadores.",
        "sagittarius": "Valoriza a liberdade e o crescimento pessoal nos relacionamentos. Gosta de conexões que tragam aventura e aprendizado.",
        "capricorn": "Valoriza a estabilidade e a segurança material nos relacionamentos. Gosta de compromissos sérios e duradouros.",
        "aquarius": "Valoriza a individualidade e a amizade nos relacionamentos. Gosta de conexões únicas e não convencionais.",
        "pisces": "Valoriza a sensibilidade e a conexão espiritual nos relacionamentos. Procura por relacionamentos românticos e compassivos."
    },
    "mars_signs": {
        "aries": "Ação rápida e impulsiva. Gosta de desafios e age com coragem e iniciativa.",
        "taurus": "Ação lenta, mas determinada. Prefere a persistência e busca resultados concretos.",
        "gemini": "Ação através das palavras e do intelecto. Gosta de variedade e age com flexibilidade.",
        "cancer": "Ação guiada pelas emoções. Protege e defende o que ama, mas pode agir de forma indireta.",
        "leo": "Ação com confiança e brilho. Busca destaque e age com criatividade e paixão.",
        "virgo": "Ação prática e detalhista. Prefere a eficiência e resolve problemas de maneira meticulosa.",
        "libra": "Ação equilibrada e diplomática. Busca agir de forma justa, mas pode hesitar ao tomar decisões.",
        "scorpio": "Ação intensa e focada. Gosta de profundidade e age com grande determinação e estratégia.",
        "sagittarius": "Ação expansiva e aventureira. Busca novas experiências e age com entusiasmo e otimismo.",
        "capricorn": "Ação disciplinada e ambiciosa. Focado em resultados a longo prazo, age com responsabilidade e persistência.",
        "aquarius": "Ação inovadora e independente. Gosta de agir de forma original e não convencional.",
        "pisces": "Ação guiada pela intuição e compaixão. Age de maneira sensível, mas pode ser passivo ou evasivo."
    },
    "jupiter_signs": {
        "aries": "Expansão através da iniciativa e coragem. Confiança em tomar riscos e liderar.",
        "taurus": "Expansão através da estabilidade e da busca por segurança material. Valoriza o conforto e o prazer.",
        "gemini": "Expansão através da comunicação e aprendizado. Gosta de explorar diferentes ideias e conhecimentos.",
        "cancer": "Expansão através das emoções e do cuidado com os outros. Sente-se realizado ao nutrir e proteger.",
        "leo": "Expansão através da criatividade e autoconfiança. Busca o crescimento pessoal e a autoexpressão.",
        "virgo": "Expansão através do trabalho e do aperfeiçoamento pessoal. Crescimento vem da organização e do serviço.",
        "libra": "Expansão através dos relacionamentos e da busca por equilíbrio. Valoriza a justiça e a harmonia social.",
        "scorpio": "Expansão através da profundidade emocional e da transformação. Busca crescer por meio de crises e desafios.",
        "sagittarius": "Expansão através da aventura, do conhecimento e da liberdade. Busca significado e sabedoria nas experiências.",
        "capricorn": "Expansão através do trabalho duro e da ambição. Cresce de forma estruturada e com foco em resultados a longo prazo.",
        "aquarius": "Expansão através de ideias progressistas e da inovação. Crescimento vem do coletivo e da originalidade.",
        "pisces": "Expansão através da espiritualidade, da compaixão e da imaginação. Busca o crescimento emocional e transcendente."
    },
    "saturn_signs": {
        "aries": "Desafios em assumir liderança e agir com impulso. Precisa aprender a ser mais disciplinado e estratégico.",
        "taurus": "Desafios em questões de segurança material e estabilidade. Ensina a importância da paciência e do trabalho duro.",
        "gemini": "Desafios na comunicação e no aprendizado. Necessidade de organizar pensamentos e ser mais consistente nas ideias.",
        "cancer": "Desafios emocionais e na segurança pessoal. Ensina a lidar com vulnerabilidades e a construir laços estáveis.",
        "leo": "Desafios na autoexpressão e na busca por reconhecimento. Ensina a desenvolver confiança através do esforço e da humildade.",
        "virgo": "Desafios no perfeccionismo e na crítica. Ensina a importância da eficiência e da aceitação das imperfeições.",
        "libra": "Desafios em relacionamentos e na busca por equilíbrio. Ensina a construir parcerias sólidas e justas.",
        "scorpio": "Desafios com controle e poder. Ensina a transformação profunda e a lidar com medos e crises de forma madura.",
        "sagittarius": "Desafios em encontrar um sentido de vida ou propósito. Ensina a importância de estrutura e foco para atingir ideais elevados.",
        "capricorn": "Desafios em aceitar responsabilidades e ambições. Ensina a importância do trabalho árduo e da persistência para alcançar o sucesso.",
        "aquarius": "Desafios com a inovação e o senso de comunidade. Ensina a responsabilidade social e a necessidade de estrutura no progresso.",
        "pisces": "Desafios com a sensibilidade e os limites pessoais. Ensina a importância de equilibrar espiritualidade e realidade."
    },
    "uranus_signs": {
        "aries": "Inovações através da ação e da coragem. Traz mudanças rápidas e inesperadas, com ênfase na independência.",
        "taurus": "Revolução nas questões materiais e de segurança. Desafia o apego à estabilidade e valoriza novas abordagens à riqueza e ao conforto.",
        "gemini": "Inovações na comunicação e no aprendizado. Estimula formas alternativas de pensar e compartilhar ideias.",
        "cancer": "Mudanças profundas nas emoções e na vida familiar. Desafia as tradições domésticas e incentiva novas formas de criar laços emocionais.",
        "leo": "Inovações na autoexpressão e no desejo de ser único. Desafia o ego e incentiva novas formas criativas de se destacar.",
        "virgo": "Mudanças no trabalho, saúde e rotina. Estimula métodos inovadores de organização e eficiência.",
        "libra": "Revoluções nos relacionamentos e na busca por justiça. Traz mudanças inesperadas nas parcerias e desafia a forma como nos conectamos aos outros.",
        "scorpio": "Transformações radicais na intimidade e no poder pessoal. Desafia o controle e traz inovações em questões profundas e ocultas.",
        "sagittarius": "Mudanças na filosofia de vida, educação e viagens. Estimula a busca por novas visões e formas de explorar o mundo.",
        "capricorn": "Revoluções nas estruturas sociais e ambições. Desafia as convenções e traz mudanças no sistema e na maneira como buscamos o sucesso.",
        "aquarius": "Inovações no coletivo e na individualidade. Estimula o progresso social, a tecnologia e a liberdade pessoal.",
        "pisces": "Mudanças na espiritualidade e na criatividade. Desafia as fronteiras entre o consciente e o inconsciente, estimulando novas formas de perceber a realidade."
    },
    "neptune_signs": {
        "aries": "Inspiração e sonhos ligados à ação e à coragem. Pode trazer ilusões sobre liderança ou uma espiritualidade centrada na iniciativa.",
        "taurus": "Fantasias e ideais sobre segurança e conforto. Desafia a percepção de estabilidade e valores materiais, com inclinação para o desapego.",
        "gemini": "Confusão e imaginação na comunicação e nas ideias. Pode trazer uma mente intuitiva, mas também dispersão e dificuldade em focar.",
        "cancer": "Sensibilidade extrema em relação às emoções e à família. Pode idealizar a vida doméstica ou sentir forte empatia por questões familiares.",
        "leo": "Sonhos e ilusões ligados ao ego e à expressão pessoal. Pode trazer a busca por uma identidade grandiosa ou artística, mas também a perda de identidade.",
        "virgo": "Idealismo no trabalho e na saúde. Pode trazer um desejo de perfeição irrealista ou sacrifícios em busca de um ideal prático.",
        "libra": "Idealização nos relacionamentos e na busca por harmonia. Pode haver dificuldade em ver parcerias de forma realista ou uma tendência a romantizar excessivamente.",
        "scorpio": "Intuição e mistério profundos na intimidade e no poder pessoal. Pode haver confusão sobre os próprios desejos e uma busca por transcendência emocional.",
        "sagittarius": "Sonhos ligados à filosofia, religião e viagens. Pode trazer uma busca por significado espiritual ou uma visão utópica do mundo.",
        "capricorn": "Idealismo nas ambições e na estrutura social. Pode haver ilusões sobre o sucesso ou a carreira, mas também uma visão espiritual do trabalho.",
        "aquarius": "Inspiração em causas humanitárias e progressistas. Traz uma visão idealista sobre a sociedade e a tecnologia, buscando a elevação coletiva.",
        "pisces": "Espiritualidade intensa e profunda conexão com o inconsciente. Traz uma sensibilidade extrema, empatia e forte tendência à imaginação e ao escapismo."
    },
    "pluto_signs": {
        "aries": "Transformação através da ação e do impulso. Pode trazer regeneração através de desafios pessoais, crises de identidade e redefinição da própria força.",
        "taurus": "Transformação nos valores e posses materiais. Pode gerar mudanças radicais em relação ao dinheiro, segurança e apego ao que é estável.",
        "gemini": "Mudança profunda na comunicação e nas ideias. Traz uma mente intensa, investigativa, mas também transformações nas maneiras de aprender e expressar-se.",
        "cancer": "Transformação emocional ligada à família e às raízes. Pode gerar crises intensas relacionadas ao lar, à segurança emocional e à ancestralidade.",
        "leo": "Transformação através da expressão pessoal e do ego. Traz uma necessidade de reinventar a identidade, com crises de poder e orgulho pessoal.",
        "virgo": "Transformação no trabalho, saúde e rotinas. Traz mudanças profundas na forma de cuidar do corpo e dos detalhes da vida cotidiana.",
        "libra": "Transformação nas relações e nas parcerias. Pode gerar crises em casamentos e sociedades, forçando a redefinição de equilíbrio e justiça.",
        "scorpio": "Transformação profunda em áreas de poder, controle e sexualidade. É a posição mais intensa de Plutão, indicando crises que levam à renovação completa.",
        "sagittarius": "Transformação em crenças, filosofias e expansão mental. Pode trazer mudanças radicais em conceitos espirituais, religião e o sentido da vida.",
        "capricorn": "Transformação nas estruturas sociais e ambições. Traz crises em torno de carreira, status e autoridade, levando a uma redefinição de sucesso e poder.",
        "aquarius": "Transformação nas causas coletivas e tecnologia. Pode indicar revoluções sociais e profundas mudanças nos ideais progressistas e na forma de se conectar com grupos.",
        "pisces": "Transformação espiritual e emocional profunda. Traz crises ligadas à espiritualidade, fantasia e sacrifício, com uma busca intensa por redenção e compreensão do inconsciente."
    }
}
